services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  user-backend:
    build: ./User
    ports:
      - "8000:8000"
    volumes:
      - ./User:/app
      - user_sqlite:/app/db

    depends_on:
      redis:
        condition: service_healthy

  driver-backend:
    build: ./Driver
    ports:
      - "8002:8002"
    volumes:
      - ./Driver:/app
      - driver_sqlite:/app/db

    depends_on:
      redis:
        condition: service_healthy
      user-backend:
        condition: service_started

  order-backend:
    build: ./Order
    ports:
      - "8001:8001"
    volumes:
      - ./Order:/app
      - order_sqlite:/app/db

    depends_on:
      redis:
        condition: service_healthy
      driver-backend:
        condition: service_started

  telegram-bot:
    build: ./SanyaBot
    volumes:
      - ./SanyaBot:/app

    depends_on:
      user-backend:
        condition: service_started
      order-backend:
        condition: service_started
      driver-backend:
        condition: service_started
    restart: unless-stopped

volumes:
  redis_data:
  user_sqlite:
  driver_sqlite:
  order_sqlite:
