"""Абстракции-шлюзы к бэкенду (порты).

Прикладные сервисы зависят ТОЛЬКО от этих протоколов, а не от httpx или
конкретного REST-клиента (принцип инверсии зависимостей, DIP). Протоколы
узкие и разбиты по контекстам (принцип разделения интерфейсов, ISP),
чтобы сервис не зависел от методов, которые ему не нужны.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from app.domain.commands import NewOffer, NewOrder, RegisterUser
from app.domain.models import Offer, Order, Resource, User


class UserGateway(Protocol):
    async def find_by_telegram_id(self, telegram_user_id: str) -> User | None: ...

    async def find_by_phone(self, phone: str) -> User | None: ...

    async def register(self, command: RegisterUser) -> User: ...

    async def link_telegram(self, telegram_user_id: str, phone: str) -> User: ...


class ResourceGateway(Protocol):
    async def list_active(self) -> Sequence[Resource]: ...


class OrderGateway(Protocol):
    async def create(self, user_id: str, command: NewOrder) -> Order: ...

    async def get(self, order_id: str) -> Order: ...

    async def list_by_user(self, user_id: str) -> Sequence[Order]: ...

    async def list_by_driver(self, user_id: str) -> Sequence[Order]: ...

    async def list_available(self) -> Sequence[Order]: ...

    async def accept_offer(self, user_id: str, order_id: str, offer_id: str) -> Order: ...

    async def start(self, user_id: str, order_id: str) -> Order: ...

    async def complete(self, user_id: str, order_id: str) -> Order: ...

    async def cancel(self, user_id: str, order_id: str) -> Order: ...

    async def driver_withdraw(self, user_id: str, order_id: str) -> Order: ...


class OfferGateway(Protocol):
    async def list_for_order(self, user_id: str, order_id: str) -> Sequence[Offer]: ...

    async def list_for_driver(self, user_id: str) -> Sequence[Offer]: ...

    async def create(self, user_id: str, command: NewOffer) -> Offer: ...

    async def withdraw(self, user_id: str, offer_id: str) -> Offer: ...
