services:
  user-backend:
    build:
      context: ..
      dockerfile: User/Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_PORT: 8000
    env_file:
      - .env
    restart: unless-stopped